# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: devops-project
  labels:
    app: devops-project
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: devops-project
  type: NodePort
